version: "3.9"

services:
  db:
    image: postgres:15
    container_name: optcg-db
    restart: always
    environment:
      POSTGRES_USER: skyler
      POSTGRES_PASSWORD: password
      POSTGRES_DB: optcg_stats
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
